# DOTA数据集配置
path: ./data/DOTA
train: images/train
val: images/val
test: images/test

# Classes (顺序必须与训练时保持一致!)
names:
  0: plane
  1: ship
  2: storage-tank
  3: baseball-diamond
  4: tennis-court
  5: basketball-court
  6: ground-track-field
  7: harbor
  8: bridge
  9: large-vehicle
  10: small-vehicle
  11: helicopter
  12: roundabout
  13: soccer-ball-field
  14: swimming-pool
nc: 15

# Dataset configuration
dataset:
  image_size: 1024
  augmentation: true
  mosaic: 1.0
  mixup: 0.0
